apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-service-account-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: pod-service-account 
  namespace: {{ include "pod-sevice-account.namespace" . }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-service-account-cluster-role 