apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pod-sevice-account.fullname" . }}
  labels:
    {{- include "pod-sevice-account.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}